[project]
name = "pykit"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "filelock>=3.18.0",
    "matplotlib",
    "pint",
    "pydantic>=2.6.4",
    "pytest",
]
