[project]
name = "pykit"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "pint>=0.24.4",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
]
